//
//  DummyCandies.swift
//  CandiAppIos
//
//  Copyright © 2020 Nusantarian. All rights reserved.
//

import UIKit

var candies: [Candi] = [
    Candi(photo: UIImage(named: "pic_badut")!, title: "Candi Badut", desc: "Candi Badhut ditemukan oleh pakar arkeologi di tahun 1923. Candi yang juga disebut Candi Liswa ini berlokasi kurang lebih 5 km dari kota Malang, tepatnya di Desa Karangbesuki, Kecamatan Dau, Kabupaten Malang, Jawa Timur. Candi Badhut diduga diperkirakan dibangun jauh sebelum masa pemerintahan Airlangga, yaitu masa dimulainya pembangunan candi-candi lain di Jawa Timur, dan diduga merupakan candi tertua di Jawa Timur"),
    Candi(photo: UIImage(named: "pic_borobudur")!, title: "Candi Borobudur", desc: "Candi Borobudur adalah sebuah candi Buddha yang terletak di Borobudur, Magelang, Jawa Tengah, Indonesia. Candi ini terletak kurang lebih 100 km di sebelah barat daya Semarang, 86 km di sebelah barat Surakarta, dan 40 km di sebelah barat laut Yogyakarta. Candi berbentuk stupa ini didirikan oleh para penganut agama Buddha Mahayana sekitar tahun 800-an Masehi pada masa pemerintahan wangsa Syailendra. Borobudur adalah candi atau kuil Buddha terbesar di dunia"),
    Candi(photo: UIImage(named: "pic_singosari")!, title: "Candi Singasari", desc: "Candi Singasari terletak di Desa Candi Renggo, Kecamatan Singosari, Kabupaten Malang, kurang lebih 9 Km dari kota Malang ke arah Surabaya. Candi ini juga dikenal dengan nama Candi Cungkup atau Candi Menara, nama yang menunjukkan bahwa Candi Singasari adalah candi yang tertinggi pada masanya, setidaknya dibandingkan dengan candi lain di sekelilingnya. Akan tetapi, saat ini di kawasan Singasari hanya candi Singasari yang masih tersisa, sedangkan candi lainnya telah lenyap tak berbekas"),
    Candi(photo: UIImage(named: "pic_plaosan")!, title: "Candi Plaosan", desc: "Candi Plaosan terletak di Desa Bugisan, Kecamatan Prambanan, Kabupaten Klaten, kira-kira 1,5 km ke arah timur dari Candi Sewu. Candi ini merupakan sebuah kompleks bangunan kuno yang terbagi menjadi dua, yaitu kompleks Candi Plaosan Lor (lor dalam bahasa Jawa berarti utara) dan kompleks Candi Plaosan Kidul (kidul dalam bahasa Jawa berarti selatan). Pahatan yang terdapat di Candi Plaosan sangat halus dan rinci, mirip dengan yang terdapat di Candi Borobudur, Candi Sewu, dan Candi Sari"),
    Candi(photo: UIImage(named: "pic_muara_takus")!, title: "Candi Muara Takus", desc: "Candi Muara Takus terletak di desa Muara Takus, Kecamatan Tigabelas Koto Kampar, Kabupaten Kampar, Propinsi Riau. Jaraknya dari Pekanbaru, Ibukota Propinsi Riau, sekitar 128 Km. Perjalanan menuju Desa Muara Takus hanya dapat dilakukan melalui jalan darat yaitu dari Pekanbaru ke arah Bukittinggi sampai di Muara Mahat. Dari Muara Mahat melalui jalan kecil menuju ke Desa Muara Takus. Kompleks Candi Muara Takus, satu-satunya peninggalan sejarah yang berbentuk candi di Riau. Candi bernuansa Buddhistis ini merupakan bukti bahwa agama Budha pernah berkembang di kawasan ini. Kendatipun demikian, para pakar purbakala belum dapat menentukan secara pasti kapan candi ini didirikan"),
    Candi(photo: UIImage(named: "pic_pawon")!, title: "Candi Pawon", desc: "Candi Pawon terletak di Desa Borobudur, Kecamatan Borobudur, Kabupaten Magelang, Propinsi Jawa Tengah. Candi yang mempunyai nama lain Candi Brajanalan ini lokasinya sekitar 2 km ke arah timur laut dari Candi Barabudhur dan 1 km ke arah tenggara dari Candi Mendut. Letak Candi Mendut, Candi Pawon dan Candi Barabudhur yang berada pada satu garis lurus mendasari dugaan bahwa ketiga candi Buddha tersebut mempunyai kaitan yang erat. Selain letaknya, kemiripan motif pahatan di ketiga candi tersebut juga mendasari adanya keterkaitan di antara ketiganya. Poerbatjaraka, bahkan berpendapat bahwa candi Pawon merupakan upa angga (bagian dari) Candi Barabudhur"),
    Candi(photo: UIImage(named: "pic_kidal")!, title: "Candi Kidal", desc: "Candi Kidal terletak di Desa Rejokidal, Kecamatan Tumpang, Kabupaten Malang, tepatnya sekitar 20 km ke arah timur dari kota Malang. Candi ini dapat dikatakan merupakan candi pemujaan yang paling tua di Jawa Timur, karena pemerintahan Airlangga (11–12 M) dari Kerajaan Kahuripan dan raja-raja Kerajaan Kediri (12endash13 M) hanya meninggalkan Candi Belahan dan Jalatunda yang merupakan petirtaan atau pemandian"),
    Candi(photo: UIImage(named: "pic_prambanan")!, title: "Candi Prambanan", desc: "Candi Prambanan terletak di lingkungan Taman Wisata Prambanan, kurang lebih 17 km ke arah timur dari Yogyakarta, tepatnya di Desa Prambanan Kecamatan Bokoharjo. Lokasinya hanya sekitar 100 m dari jalan raya Yogya-Solo, sehingga tidak sulit untuk menemukannya. Sebagian dari kawasan wisata yang terletak pada ketinggian 154 m di atas permukaan laut ini termasuk dalam wilayah Kabupaten Sleman. sedangkan sebagian lagi masuk dalam wilayah Klaten"),
    Candi(photo: UIImage(named: "pic_jawi")!, title: "Candi Jawi", desc: "Candi Jawi terletak di kaki G. Welirang, tepatnya di Desa Candi Wates, Kecamatan Prigen, Kabupaten Pasuruan, sekitar 31 km dari kota Pasuruan. Bangunan candi dapat dikatakan masih utuh karena telah berkali–kali mengalami pemugaran. Candi Jawi dipugar untuk kedua kalinya tahun 1938 sampai 1941 dari kondisinya yang sudah runtuh. Akan tetapi, pemugaran tidak dapat dituntaskan karena banyak batu yang hilang dan baru disempurnakan pada tahun 1975 sampai 1980"),
    Candi(photo: UIImage(named: "pic_penataran")!, title: "Candi Penataran", desc: "Candi Panataran terletak di lereng barat daya Gunung Kelud, sekitar 12 km ke arah utara dari Kota Blitar, tepatnya di Desa Panataran, Kecamatan Ngleggok, Kabupaten Blitar. Candi ini merupakan sekumpulan bangunan kuno yang berjajar dari barat-laut ke timur kemudian berlanjut ke tenggara, menempati lahan seluas 12.946 m2")
]

